### ISSUE TITLE
content-script.js isn't UTF-8 encoded

### ISSUE THREAD

**Issue by codingant007** [lukehorvat/github-ast-viewer#4]
While installing this extension through chrome web store I encounter the following error
![screenshot from 2016-10-05 02-17-56](https://cloud.githubusercontent.com/assets/7330399/19092187/2e6c03ec-8aa3-11e6-8759-0e4a75a6a202.png)

**Comment by mgroth0** [comment]
I got the same error
![image](https://cloud.githubusercontent.com/assets/12831489/23828257/66fd3960-069a-11e7-9a61-6ec2fdb90870.png)

**Comment by psykokwak4** [comment]
Same error, is there a workaround for this error?

**Comment by lukehorvat** [comment]
Thanks for the report, folks.

It looks like Esprima v2.3.0 (and newer) screws with the encoding of the Browserified content script. As a temporary fix, I've reverted Esprima to v2.2.0 and published a new version of the extension, v1.0.5.
 
In the long-term, I'm probably going to drop Esprima in favor of [Babylon](https://github.com/babel/babylon).
